// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxMcZMFtlQcfTD9xqYzUieaL8i6bSZMXM',
    appId: '1:737381494777:web:7405a00b64bc8585b15728',
    messagingSenderId: '737381494777',
    projectId: 'authtutorial-b1d10',
    authDomain: 'authtutorial-b1d10.firebaseapp.com',
    storageBucket: 'authtutorial-b1d10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzF9J1vp5kqebIednvywo4-2cpqAC2q4w',
    appId: '1:737381494777:android:754cc8c392457b7fb15728',
    messagingSenderId: '737381494777',
    projectId: 'authtutorial-b1d10',
    storageBucket: 'authtutorial-b1d10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAidt5wmzMWv5JKBQZgd9hBDh-ODyjOQtY',
    appId: '1:737381494777:ios:a37589e0f4c90bd6b15728',
    messagingSenderId: '737381494777',
    projectId: 'authtutorial-b1d10',
    storageBucket: 'authtutorial-b1d10.appspot.com',
    iosClientId: '737381494777-3ocpq51sfesd9tve1ks7t24p9irrf3j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAidt5wmzMWv5JKBQZgd9hBDh-ODyjOQtY',
    appId: '1:737381494777:ios:a37589e0f4c90bd6b15728',
    messagingSenderId: '737381494777',
    projectId: 'authtutorial-b1d10',
    storageBucket: 'authtutorial-b1d10.appspot.com',
    iosClientId: '737381494777-3ocpq51sfesd9tve1ks7t24p9irrf3j4.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkupApp',
  );
}
